repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/pylint
    rev: v3.0.1
    hooks:
    -   id: pylint
        args:
          - --ignore-paths=^tests/.*$
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.12.0
    hooks:
      - id: commitizen
        stages: [ commit-msg ]

  - repo: https://github.com/IBM/detect-secrets
    rev: v0.13.1
    hooks:
      - id: detect-secrets

  - repo: local
    hooks:
      - id: pytest-cov
        name: pytest
        stages: [pre-push]
        language: system
        entry: pipenv run tests
        types: [python]
        pass_filenames: false
